[[redirects]]
  from = "/"
  to = "/index.static.html"
  status = 200
  force = true
  conditions = {User-Agent = ["*bot*", "*Bot*", "*Crawler*", "*Spider*"]}

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
