[[redirects]]
  from = "https://resorensonllc.com/*"
  to = "https://lattara.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://resorensonllc.com/*"
  to = "https://lattara.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/seo.html"
  status = 200
  force = true
  conditions = {User-Agent = ["*bot*", "*Bot*", "*spider*", "*Spider*", "*crawler*", "*Crawler*", "Googlebot", "Bingbot", "Slurp", "DuckDuckBot", "Baiduspider", "YandexBot", "facebookexternalhit", "TwitterBot", "WhatsApp", "LinkedInBot", "Slack"]}

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
